In [2]:
import numpy as np
import pandas as pd
import scipy as sp
import matplotlib as mpl
import sklearn as skl

In [3]:
np

<module 'numpy' from '/home/aakef/.local/lib/python3.6/site-packages/numpy/__init__.py'>

In [4]:
pd

<module 'pandas' from '/home/aakef/.local/lib/python3.6/site-packages/pandas/__init__.py'>

In [5]:
sp

<module 'scipy' from '/home/aakef/.local/lib/python3.6/site-packages/scipy/__init__.py'>

In [6]:
mpl

<module 'matplotlib' from '/home/aakef/.local/lib/python3.6/site-packages/matplotlib/__init__.py'>

In [7]:
skl

<module 'sklearn' from '/home/aakef/.local/lib/python3.6/site-packages/sklearn/__init__.py'>

# Numpy Stuff

In [8]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

In [9]:
arr1.ndim


1

In [10]:
arr1.shape

(3,)

In [11]:
arr3 = np.array([arr1.data, arr2.data])

In [12]:
arr3

array([[1, 2, 3],
       [1, 2, 3]])

In [13]:

arr3.shape

(2, 3)

In [14]:
arr3.ndim

2

In [15]:
arr3.dtype

dtype('int64')

In [16]:
arr1.dtype


dtype('int64')

In [17]:

arr3[1]

array([1, 2, 3])

In [18]:
arr3[1, 2]

3

In [19]:
arr3[-1, -2]

2

In [20]:
# Get a row
arr3[0, :]

array([1, 2, 3])

In [21]:
# Get a column
arr3[:, 0]

array([1, 1])

In [22]:
arr3[1, 1] = 10

In [23]:
arr2

array([1, 2, 3])

In [24]:
arr3

array([[ 1,  2,  3],
       [ 1, 10,  3]])

In [25]:
arr3[0] = [7, 8, 0]

In [26]:
arr3

array([[ 7,  8,  0],
       [ 1, 10,  3]])

In [27]:
np.zeros((10, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [28]:
np.ones((3, 6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [29]:
np.full((2, 4), 73)

array([[73, 73, 73, 73],
       [73, 73, 73, 73]])

In [30]:
a = np.full((2, 3), 3)
b = np.full((3, 2), 4)

In [31]:
print(a)
print(b)

[[3 3 3]
 [3 3 3]]
[[4 4]
 [4 4]
 [4 4]]


In [32]:
np.matmul(a, b)

array([[36, 36],
       [36, 36]])

In [33]:
np.matmul(b, a)

array([[24, 24, 24],
       [24, 24, 24],
       [24, 24, 24]])

In [34]:
iden = np.identity(3)

In [35]:
iden

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
np.linalg.det(iden)

1.0

In [37]:
np.linalg.eig(iden)

(array([1., 1., 1.]), array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))

In [38]:
stats = np.array([[1, 2, 3], [4, 5, 6]])
np.min(stats)

1

In [39]:
np.max(stats, axis=1)

array([3, 6])

In [42]:
np.sort(iden)

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]])

# Pandas

In [45]:
df = pd.read_csv('netflix_titles_nov_2019.csv')
df

show_id                                title  \
0     81193313                            Chocolate   
1     81197050  Guatemala: Heart of the Mayan World   
2     81213894                      The Zoya Factor   
3     81082007                            Atlantics   
4     80213643                      Chip and Potato   
...        ...                                  ...   
5832  70141644          Mad Ron's Prevues from Hell   
5833  70127998                             Splatter   
5834  70084180              Just Another Love Story   
5835  70157452                      Dinner for Five   
5836  70053412                 To and From New York   

                        director  \
0                            NaN   
1     Luis Ara, Ignacio Jaunsolo   
2                Abhishek Sharma   
3                      Mati Diop   
4                            NaN   
...                          ...   
5832                  Jim Monaco   
5833                   Joe Dante   
5834                Ole Bornedal   
5835                         NaN   
5836        Sorin Dan Mihalcescu   

                                                   cast  \
0     Ha Ji-won, Yoon Kye-sang, Jang Seung-jo, Kang ...   
1                                     Christian Morales   
2     Sonam Kapoor, Dulquer Salmaan, Sanjay Kapoor, ...   
3     Mama Sane, Amadou Mbow, Ibrahima Traore, Nicol...   
4     Abigail Oliver, Andrea Libman, Briana Buckmast...   
...                                                 ...   
5832  Nick Pawlow, Jordu Schell, Jay Kushwara, Micha...   
5833  Corey Feldman, Tony Todd, Tara Leigh, Erin Way...   
5834  Anders W. Berthelsen, Rebecka Hemse, Nikolaj L...   
5835                                                NaN   
5836  Barbara King, Shaana Diya, John Krisiukenas, Y...   

                       country         date_added  release_year rating  \
0                  South Korea  November 30, 2019          2019  TV-14   
1                          NaN  November 30, 2019          2019   TV-G   
2                        India  November 30, 2019          2019  TV-14   
3     France, Senegal, Belgium  November 29, 2019          2019  TV-14   
4       Canada, United Kingdom                NaN          2019   TV-Y   
...                        ...                ...           ...    ...   
5832             United States   November 1, 2010          1987     NR   
5833             United States  November 18, 2009          2009  TV-14   
5834                   Denmark        May 5, 2009          2007     NR   
5835             United States   February 4, 2008          2007  TV-MA   
5836             United States    January 1, 2008          2006     NR   

       duration                                          listed_in  \
0      1 Season  International TV Shows, Korean TV Shows, Roman...   
1        67 min                Documentaries, International Movies   
2       135 min             Comedies, Dramas, International Movies   
3       106 min   Dramas, Independent Movies, International Movies   
4     2 Seasons                                           Kids' TV   
...         ...                                                ...   
5832     84 min                         Cult Movies, Horror Movies   
5833     29 min                                      Horror Movies   
5834    104 min                       Dramas, International Movies   
5835   1 Season                       Stand-Up Comedy & Talk Shows   
5836     81 min              Dramas, Independent Movies, Thrillers   

                                            description     type  
0     Brought together by meaningful meals in the pa...  TV Show  
1     From Sierra de las Minas to Esquipulas, explor...    Movie  
2     A goofy copywriter unwittingly convinces the I...    Movie  
3     Arranged to marry a rich man, young Ada is cru...    Movie  
4     Lovable pug Chip starts kindergarten, makes ne...  TV Show  
...                                                 ...      ...  
5832 

In [46]:
df.shape

(5837, 12)

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5837 entries, 0 to 5836
Data columns (total 12 columns):
show_id         5837 non-null int64
title           5837 non-null object
director        3936 non-null object
cast            5281 non-null object
country         5410 non-null object
date_added      5195 non-null object
release_year    5837 non-null int64
rating          5827 non-null object
duration        5837 non-null object
listed_in       5837 non-null object
description     5837 non-null object
type            5837 non-null object
dtypes: int64(2), object(10)
memory usage: 547.3+ KB


In [48]:
len(df)

5837