In [1]:
import numpy as np
import pandas as pd
import scipy as sp
import matplotlib as mpl
import sklearn as skl

In [2]:
np

<module 'numpy' from '/home/aakef/.local/lib/python3.6/site-packages/numpy/__init__.py'>

In [3]:
pd

<module 'pandas' from '/home/aakef/.local/lib/python3.6/site-packages/pandas/__init__.py'>

In [4]:
sp

<module 'scipy' from '/home/aakef/.local/lib/python3.6/site-packages/scipy/__init__.py'>

In [5]:
mpl

<module 'matplotlib' from '/home/aakef/.local/lib/python3.6/site-packages/matplotlib/__init__.py'>

In [6]:
skl

<module 'sklearn' from '/home/aakef/.local/lib/python3.6/site-packages/sklearn/__init__.py'>

# Numpy Stuff

In [7]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

In [10]:
arr1.ndim


1

In [12]:
arr1.shape

(3,)

In [16]:
arr3 = np.array([arr1.data, arr2.data])

In [17]:
arr3

array([[1, 2, 3],
       [1, 2, 3]])

In [18]:

arr3.shape

(2, 3)

In [19]:
arr3.ndim

2

In [20]:
arr3.dtype

dtype('int64')

In [21]:
arr1.dtype


dtype('int64')

In [23]:

arr3[1]

array([1, 2, 3])

In [24]:
arr3[1, 2]

3

In [25]:
arr3[-1, -2]

2

In [26]:
# Get a row
arr3[0, :]

array([1, 2, 3])

In [27]:
# Get a column
arr3[:, 0]

array([1, 1])

In [28]:
arr3[1, 1] = 10

In [29]:
arr2

array([1, 2, 3])

In [30]:
arr3

array([[ 1,  2,  3],
       [ 1, 10,  3]])

In [31]:
arr3[0] = [7, 8, 0]

In [32]:
arr3

array([[ 7,  8,  0],
       [ 1, 10,  3]])

In [35]:
np.zeros((10, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [36]:
np.ones((3, 6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [37]:
np.full((2, 4), 73)

array([[73, 73, 73, 73],
       [73, 73, 73, 73]])

In [43]:
a = np.full((2, 3), 3)
b = np.full((3, 2), 4)

In [44]:
print(a)
print(b)

[[3 3 3]
 [3 3 3]]
[[4 4]
 [4 4]
 [4 4]]


In [45]:
np.matmul(a, b)

array([[36, 36],
       [36, 36]])

In [46]:
np.matmul(b, a)

array([[24, 24, 24],
       [24, 24, 24],
       [24, 24, 24]])

In [47]:
iden = np.identity(3)

In [48]:
iden

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [49]:
np.linalg.det(iden)

1.0

In [50]:
np.linalg.eig(iden)

(array([1., 1., 1.]), array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))

In [53]:
stats = np.array([[1, 2, 3], [4, 5, 6]])
np.min(stats)

1

In [55]:
np.max(stats, axis=1)

array([3, 6])

In [56]:
np.sort(iden)

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]])

In [ ]:
np.reshape(1, 9)